services: 
  telaclass_react-app:
    build:
      context: . 
      dockerfile: Dockerfile
    image: telaclass-i
    container_name: telaclass_react-app-c
    volumes:
      - ./react-app:/app/react-app
    ports: 
      - "3000:3000"
    command: ["/bin/bash", "-c", "cd /app/react-app && npm install && npm start"]

  telaclass_content-server-api:
    build:
      context: . 
      dockerfile: Dockerfile
    image: telaclass-i
    container_name: telaclass_content-server-api-c
    volumes:
      - ./content-server-api:/app/content-server-api
      # the path to the discipline's obsidian vault folder
      # ATUALIZAR ESTE PATH
      - /Users/filgusto/pCloud Drive/fil-pcl/trabalhos/2024_ufsj/disciplinas/EM03110817_sistemas-supervisorios/material/obsidian/content_supervisorios:/app/obsidian-content
    ports: 
      - "3001:3001"
    command: ["/bin/bash", "-c", "cd /app/content-server-api && npm install && node content-server.js"]


    